export type LoginMethod = 'email' | 'wechat';
export type PaymentMethod = 'alipay' | 'wechat';
export type Tier = 'standard' | 'premium';
export type Cycle = 'month' | 'year';
export type Gender = 'M' | 'F';
export type Platform = 'web' | 'ios' | 'android'
export type SubStatus = 'active' | 'canceled' | 'incomplete' | 'incomplate_expired' | 'past_due' | 'trialing' | 'unpaid';
export type OrderType = 'create' | 'renew' | 'upgrade';
export type AccountKind = 'ftc' | 'wechat';
export type ApiKeyKind = 'app' | 'personal';
export type ActivityKind = 'login' | 'signup' | 'email_verification' | 'password_reset';
